# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'PropertyApp' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!
# Pods for PropertyApp
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'DZNEmptyDataSet'
pod 'UITextView+Placeholder'
pod 'SVProgressHUD'
end
