# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'DuXueZhuShou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DuXueZhuShou
pod 'FLAnimatedImage'
pod 'AFNetworking'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'DZNEmptyDataSet'
pod 'Charts'
pod ’SDWebImage’
pod 'Masonry'
pod 'UITextView+Placeholder'
pod 'TZImagePickerController'
pod "MJRefresh"
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'FSCalendar'
pod 'ZFPlayer'
pod 'YBImageBrowser'   
#高德
pod 'AMap3DMap' #3D地图SD
pod 'AMapLocation' #定位SDK
pod 'AMapSearch' #搜索功能

use_frameworks!

end
